version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-elikem_db}
      POSTGRES_USER: ${POSTGRES_USER:-elikem_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-elikem_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - sample_env
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DATABASE_URL: postgres://${POSTGRES_USER:-elikem_user}:${POSTGRES_PASSWORD:-elikem_pass}@db:5432/${POSTGRES_DB:-elikem_db}

volumes:
  postgres_data:
  static_volume:
  media_volume: 